name = "Jeef's Wynncraft"
author = "Jeef"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73a25b9fcbcf92cc6458050e64b4ee5618a53974f7716d8a2475c66e5a07f64"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
no-internal-hashes = true
