name = "Jeef's Wynncraft"
author = "Jeef"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2c3abbbdd0c8a1e685adf74e73988fefcdf48e0f23a4f43b4c4d20a3b3047bf"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
no-internal-hashes = true
