name = "Jeef's Wynncraft"
author = "Jeef"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e106bed781592040099c3abef86bf6c2c169cd7677494ac2dc6a8ff36c8d88d6"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
no-internal-hashes = true
